CREATE ROLE IF NOT EXISTS PATTERN_IQ;

CREATE DATABASE IF NOT EXISTS PATTERN_IQ;

GRANT USAGE ON DATABASE PATTERN_IQ TO ROLE PATTERN_IQ;
GRANT USAGE ON SCHEMA PATTERN_IQ.PUBLIC TO ROLE PATTERN_IQ;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PATTERN_IQ;

CREATE STAGE IF NOT EXISTS PATTERN_IQ.PUBLIC.SKILLS_STAGE
    COMMENT = 'Stores pattern-extract skill tarballs for CI distribution';

GRANT READ, WRITE ON STAGE PATTERN_IQ.PUBLIC.SKILLS_STAGE TO ROLE PATTERN_IQ;

CREATE TABLE IF NOT EXISTS PATTERN_IQ.PUBLIC.REUSABLE_PATTERNS (
    PATTERN_ID VARCHAR NOT NULL,
    PATTERN_NAME VARCHAR NOT NULL,
    CATEGORY VARCHAR,
    DESCRIPTION VARCHAR,
    ABSTRACTED_CODE VARCHAR(16777216),
    SOURCE_REPO_LINK VARCHAR,
    REPO_NAME VARCHAR,
    COMPLEXITY_SCORE NUMBER,
    DEPENDENCIES VARIANT,
    DEPENDENCY_GRAPH VARIANT,
    SYNTHETIC_QUERIES VARIANT,
    USAGE_NOTES VARCHAR,
    TAGS ARRAY,
    LANGUAGE VARCHAR,
    FRAMEWORK VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR,
    SEARCH_CONTENT VARCHAR(16777216),
    STARS NUMBER DEFAULT 0,
    CONSTRAINT pk_reusable_patterns PRIMARY KEY (PATTERN_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE PATTERN_IQ.PUBLIC.REUSABLE_PATTERNS TO ROLE PATTERN_IQ;

CREATE OR REPLACE CORTEX SEARCH SERVICE PATTERN_IQ.PUBLIC.PATTERN_SEARCH_SVC
    ON SEARCH_CONTENT
    PRIMARY KEY (PATTERN_ID)
    ATTRIBUTES PATTERN_NAME, CATEGORY, LANGUAGE, FRAMEWORK, REPO_NAME, STARS
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
    AS (
        SELECT
            PATTERN_ID,
            PATTERN_NAME,
            CATEGORY,
            DESCRIPTION,
            ABSTRACTED_CODE,
            SOURCE_REPO_LINK,
            REPO_NAME,
            COMPLEXITY_SCORE,
            DEPENDENCIES,
            DEPENDENCY_GRAPH,
            SYNTHETIC_QUERIES,
            USAGE_NOTES,
            TAGS,
            LANGUAGE,
            FRAMEWORK,
            UPDATED_AT,
            SEARCH_CONTENT,
            STARS
        FROM PATTERN_IQ.PUBLIC.REUSABLE_PATTERNS
    );

GRANT USAGE ON CORTEX SEARCH SERVICE PATTERN_IQ.PUBLIC.PATTERN_SEARCH_SVC TO ROLE PATTERN_IQ;

-- Stored procedure: increment star count on a pattern.
CREATE OR REPLACE PROCEDURE PATTERN_IQ.PUBLIC.STAR_PATTERN(P_PATTERN_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    UPDATE PATTERN_IQ.PUBLIC.REUSABLE_PATTERNS
        SET STARS = COALESCE(STARS, 0) + 1,
            UPDATED_AT = CURRENT_TIMESTAMP()
        WHERE PATTERN_ID = :P_PATTERN_ID;
    IF (SQLROWCOUNT = 0) THEN
        RETURN 'Pattern not found: ' || :P_PATTERN_ID;
    END IF;
    RETURN 'Starred pattern: ' || :P_PATTERN_ID;
END;

GRANT USAGE ON PROCEDURE PATTERN_IQ.PUBLIC.STAR_PATTERN(VARCHAR) TO ROLE PATTERN_IQ;

-- Stored procedure: permanently remove a pattern from the catalog.
CREATE OR REPLACE PROCEDURE PATTERN_IQ.PUBLIC.REMOVE_PATTERN(P_PATTERN_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    DELETE FROM PATTERN_IQ.PUBLIC.REUSABLE_PATTERNS
        WHERE PATTERN_ID = :P_PATTERN_ID;
    IF (SQLROWCOUNT = 0) THEN
        RETURN 'Pattern not found: ' || :P_PATTERN_ID;
    END IF;
    RETURN 'Removed pattern: ' || :P_PATTERN_ID;
END;

GRANT USAGE ON PROCEDURE PATTERN_IQ.PUBLIC.REMOVE_PATTERN(VARCHAR) TO ROLE PATTERN_IQ;

-- Grant the PATTERN_IQ role to the team CI service account.
-- The service account must already exist (see sql/service_account.sql).
GRANT ROLE PATTERN_IQ TO USER AIFDE_CI_SVC;
