DROP PROCEDURE IF EXISTS PATTERN_IQ.PUBLIC.STAR_PATTERN(VARCHAR);
DROP PROCEDURE IF EXISTS PATTERN_IQ.PUBLIC.REMOVE_PATTERN(VARCHAR);
DROP CORTEX SEARCH SERVICE IF EXISTS PATTERN_IQ.PUBLIC.PATTERN_SEARCH_SVC;
DROP TABLE IF EXISTS PATTERN_IQ.PUBLIC.REUSABLE_PATTERNS;
DROP DATABASE IF EXISTS PATTERN_IQ;
