-- Create table for purchase order line item data.
-- Each row represents an invoice line item that was matched
-- to a purchase order.
create table purchase_order_line_item (
    po_header_number text,
    po_header_wd_id text,
    po_status text,
    po_line_number text,
    created_moment text,
    po_line_wd_id text primary key,
    pr_header_number text,
    requester text,
    is_po_line_canceled integer,
    company text,
    spend_category text,
    cost_center text,
    location text,
    engagement text,
    is_excluded integer,
    capital_project_id text,
    description text,
    is_goods integer,
    quantity real,
    unit_cost real,
    is_service integer,
    service_start_date text,
    service_end_date text,
    currency text,
    purchase_order_line_amount_local real,
    purchase_order_line_amount_usd real,
    actual_amount_invoiced_local real,
    actual_amount_invoiced_usd real,
    uninvoiced_amount_local real,
    uninvoiced_amount_usd real,
    line_payment_status text,
    is_non_cancelable integer,
    deliver_to_location text,
    ship_to_address text,
    po_line_product_type text,
    is_open_line integer,
    is_po_with_open_line integer,
    is_open_po_status integer,
    report_run_date text
);

-- Table holds purchase order header data. Each row
-- represents an individual purchase order.
create table purchase_order_header_data (
    po_header_number text,
    po_header_wd_id text,
    created_date text,
    po_document_date text,
    issued_date text,
    approved_date text,
    submitted_by text,
    po_status text,
    po_header_cancellation_date text,
    supplier text,
    supplier_id text,
    payment_terms text,
    default_payment_terms text,
    version integer,
    change_order_reason text,
    transaction_currency text,
    total_po_amount_local real,
    total_po_amount_usd real,
    prior_version_po_amount_local real,
    prior_version_po_amount_usd real,
    net_amount_change_from_prior_version_local real,
    net_amount_change_from_prior_version_usd real,
    original_po_amount_local real,
    original_po_amount_usd real,
    net_amount_change_from_original_po_local real,
    net_amount_change_from_original_po_usd real,
    memo text,
    is_coupa integer,
    invoicing_status text,
    report_run_date text
);

-- Table holds list of data extracted from invoices
create table invoice_data (
    invoice_id integer primary key,
    relative_path text,
    file_url text,
    snowflake_entity text,
    vendor_name text,
    vendor_address text,
    invoice_number text,
    invoice_date date,
    total_amount real,
    tax_amount real,
    freight_shipping_amount real,
    invoice_currency text,
    purchase_order_number text,
    banking_details text,
    payment_terms text,
    memo_description text,
    shipped_to_address text,
    service_start_date date,
    service_end_date date,
    quantity real,
    unit_price real,
    payment_type text,
    due_date date,
    vendor_tax_id text,
    snowflake_tax_id text,
    prepaid_flag integer,
    created_at datetime
);
