CREATE NETWORK RULE IF NOT EXISTS <% SPCS_DATABASE_NAME %>.<% SPCS_SCHEMA_NAME %>.CDN_JSDELIVR_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('cdn.jsdelivr.net:443');

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS <% SPCS_EAI_NAME %>
  ALLOWED_NETWORK_RULES = (<% SPCS_DATABASE_NAME %>.<% SPCS_SCHEMA_NAME %>.CDN_JSDELIVR_RULE)
  ENABLED = true;
