name: streamlit_app
channels:
  - snowflake
dependencies:
  - snowflake 
  - snowflake-snowpark-python
  - pandas
  - streamlit
  - altair
  - ydata-profiling
  - trulens-core
  - trulens-providers-cortex
