config-version: 2

schemachange:
  root-folder: './schemachange'
  change-history-table: 'KNOWLEDGE_BUILDER.PUBLIC.CHANGE_HISTORY'
  create-change-history-table: true
  log-level: 'INFO'
  query-tag: 'knowledge-builder'

  vars:
    KB_DATABASE_NAME: '{{ env_var("KB_DATABASE_NAME") }}'
    KB_SCHEMA_NAME: '{{ env_var("KB_SCHEMA_NAME") }}'
    KB_WAREHOUSE_NAME: '{{ env_var("KB_WAREHOUSE_NAME", "COMPUTE_WH") }}'
    KB_SN_EAI_NAME: '{{ env_var("KB_SN_EAI_NAME", "KB_SERVICENOW_EAI") }}'
    KB_SN_SECRET_NAME: '{{ env_var("KB_SN_SECRET_NAME", "KB_SERVICENOW_SECRET") }}'
    SERVICENOW_INSTANCE_HOST: '{{ env_var("SERVICENOW_INSTANCE_HOST", "instance.service-now.com") }}'

snowflake:
  database: '{{ env_var("KB_DATABASE_NAME") }}'
