import pandas as pd
import sqlite3
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--db", type=str, required=True)
parser.add_argument("--po-header-csv", type=str, required=True)
parser.add_argument("--po-line-csv", type=str, required=True)
parser.add_argument("--invoice-csv", type=str, required=True)
args = parser.parse_args()


db = sqlite3.connect(args.db)

db.execute(
    """
CREATE TABLE IF NOT EXISTS purchase_order_line (
    PO_HEADER_NUMBER TEXT,
    PO_HEADER_WD_ID TEXT,
    PO_STATUS TEXT,
    PO_LINE_NUMBER TEXT,
    CREATED_MOMENT TEXT,
    PO_LINE_WD_ID TEXT PRIMARY KEY,
    PR_HEADER_NUMBER TEXT,
    REQUESTER TEXT,
    IS_PO_LINE_CANCELED INTEGER,
    COMPANY TEXT,
    SPEND_CATEGORY TEXT,
    COST_CENTER TEXT,
    LOCATION TEXT,
    ENGAGEMENT TEXT,
    IS_EXCLUDED INTEGER,
    CAPITAL_PROJECT_ID TEXT,
    DESCRIPTION TEXT,
    IS_GOODS INTEGER,
    QUANTITY REAL,
    UNIT_COST REAL,
    IS_SERVICE INTEGER,
    SERVICE_START_DATE TEXT,
    SERVICE_END_DATE TEXT,
    CURRENCY TEXT,
    PURCHASE_ORDER_LINE_AMOUNT_LOCAL REAL,
    PURCHASE_ORDER_LINE_AMOUNT_USD REAL,
    ACTUAL_AMOUNT_INVOICED_LOCAL REAL,
    ACTUAL_AMOUNT_INVOICED_USD REAL,
    UNINVOICED_AMOUNT_LOCAL REAL,
    UNINVOICED_AMOUNT_USD REAL,
    LINE_PAYMENT_STATUS TEXT,
    IS_NON_CANCELABLE INTEGER,
    DELIVER_TO_LOCATION TEXT,
    SHIP_TO_ADDRESS TEXT,
    PO_LINE_PRODUCT_TYPE TEXT,
    IS_OPEN_LINE INTEGER,
    IS_PO_WITH_OPEN_LINE INTEGER,
    IS_OPEN_PO_STATUS INTEGER,
    REPORT_RUN_DATE TEXT
);
"""
)

db.execute(
    """
    CREATE TABLE IF NOT EXISTS purchase_order_header (
    PO_HEADER_NUMBER TEXT,
    PO_HEADER_WD_ID TEXT,
    CREATED_DATE TEXT,
    PO_DOCUMENT_DATE TEXT,
    ISSUED_DATE TEXT,
    APPROVED_DATE TEXT,
    SUBMITTED_BY TEXT,
    PO_STATUS TEXT,
    PO_HEADER_CANCELLATION_DATE TEXT,
    SUPPLIER TEXT,
    SUPPLIER_ID TEXT,
    PAYMENT_TERMS TEXT,
    DEFAULT_PAYMENT_TERMS TEXT,
    VERSION INTEGER,
    CHANGE_ORDER_REASON TEXT,
    TRANSACTION_CURRENCY TEXT,
    TOTAL_PO_AMOUNT_LOCAL REAL,
    TOTAL_PO_AMOUNT_USD REAL,
    PRIOR_VERSION_PO_AMOUNT_LOCAL REAL,
    PRIOR_VERSION_PO_AMOUNT_USD REAL,
    NET_AMOUNT_CHANGE_FROM_PRIOR_VERSION_LOCAL REAL,
    NET_AMOUNT_CHANGE_FROM_PRIOR_VERSION_USD REAL,
    ORIGINAL_PO_AMOUNT_LOCAL REAL,
    ORIGINAL_PO_AMOUNT_USD REAL,
    NET_AMOUNT_CHANGE_FROM_ORIGINAL_PO_LOCAL REAL,
    NET_AMOUNT_CHANGE_FROM_ORIGINAL_PO_USD REAL,
    MEMO TEXT,
    IS_COUPA INTEGER,
    INVOICING_STATUS TEXT,
    REPORT_RUN_DATE TEXT
);
"""
)

db.execute(
    """
CREATE TABLE IF NOT EXISTS invoice_data (
    INVOICE_ID INTEGER PRIMARY KEY,
    RELATIVE_PATH TEXT,
    FILE_URL TEXT,
    SNOWFLAKE_ENTITY TEXT,
    VENDOR_NAME TEXT,
    VENDOR_ADDRESS TEXT,
    INVOICE_NUMBER TEXT,
    INVOICE_DATE DATE,
    TOTAL_AMOUNT REAL,
    TAX_AMOUNT REAL,
    FREIGHT_SHIPPING_AMOUNT REAL,
    INVOICE_CURRENCY TEXT,
    PURCHASE_ORDER_NUMBER TEXT,
    BANKING_DETAILS TEXT,
    PAYMENT_TERMS TEXT,
    MEMO_DESCRIPTION TEXT,
    SHIPPED_TO_ADDRESS TEXT,
    SERVICE_START_DATE DATE,
    SERVICE_END_DATE DATE,
    QUANTITY REAL,
    UNIT_PRICE REAL,
    PAYMENT_TYPE TEXT,
    DUE_DATE DATE,
    VENDOR_TAX_ID TEXT,
    SNOWFLAKE_TAX_ID TEXT,
    PREPAID_FLAG INTEGER,
    CREATED_AT DATETIME,
    STATE TEXT
);
"""
)

with open(args.po_header_csv, "r") as f:
    df = pd.read_csv(f)
    df.to_sql("purchase_order_header", db, if_exists="replace", index=False)

with open(args.po_line_csv, "r") as f:
    df = pd.read_csv(f)
    df.to_sql("purchase_order_line", db, if_exists="replace", index=False)

with open(args.invoice_csv, "r") as f:
    df = pd.read_csv(f)
    df["STATE"] = None
    df.to_sql("invoice_data", db, if_exists="replace", index=False)


db.close()

print("DONE")
