# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class Company(BaseModel):
    name: typing.Optional[str] = None
    signature_date: typing.Optional["Date"] = None

class ContractMetadata(BaseModel):
    companies: typing.List["Company"]

class Date(BaseModel):
    day: typing.Optional[int] = Field(default=None, description='The 2-digit day of the signature date')
    month: typing.Optional[int] = Field(default=None, description='The 2-digit month of the signature date')
    year: typing.Optional[int] = Field(default=None, description='The full 4-digit year of the signature date')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
