# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Company": types.Company,
    "stream_types.Company": stream_types.Company,

    "types.ContractMetadata": types.ContractMetadata,
    "stream_types.ContractMetadata": stream_types.ContractMetadata,

    "types.Date": types.Date,
    "stream_types.Date": stream_types.Date,


}