# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Citation": types.Citation,
    "stream_types.Citation": stream_types.Citation,

    "types.ContractMetadata": types.ContractMetadata,
    "stream_types.ContractMetadata": stream_types.ContractMetadata,

    "types.ContractTerm": types.ContractTerm,
    "stream_types.ContractTerm": stream_types.ContractTerm,

    "types.Date": types.Date,
    "stream_types.Date": stream_types.Date,

    "types.Party": types.Party,
    "stream_types.Party": stream_types.Party,


    "types.ContractTermCategory": types.ContractTermCategory,

    "types.PartyRole": types.PartyRole,

}