'use client'

import { useState } from 'react'
import type { ImprovementSuggestion } from '@/lib/types'
import { simulationsApi } from '@/lib/api'

interface CodeRecommendationModalProps {
  insight: ImprovementSuggestion
  simulationId: number
  isOpen: boolean
  onClose: () => void
  onIssueCreated: (issueUrl: string) => void
}

/**
 * Build GitHub issue body from insight data (mimics backend logic)
 */
function buildGithubIssueBody(insight: ImprovementSuggestion, simulationId: number): string {
  const parts: string[] = []

  // Header
  parts.push(`## ${insight.category.charAt(0).toUpperCase() + insight.category.slice(1)} Issue`)
  parts.push(`\n**Priority:** ${insight.priority.toUpperCase()}`)
  parts.push(`\n**Source:** AgentSim Simulation #${simulationId}`)
  parts.push(`\n### Description\n\n${insight.description}`)

  // Evidence section
  if (insight.evidence) {
    parts.push('\n### Evidence\n')

    if (insight.evidence.pattern) {
      parts.push(`**Pattern:** ${insight.evidence.pattern}\n`)
    }

    const convIds = insight.evidence.conversation_ids || []
    if (convIds.length > 0) {
      parts.push(`**Affected Conversations:** ${convIds.length} conversations\n`)
      parts.push(`- IDs: ${convIds.slice(0, 10).join(', ')}`)
      if (convIds.length > 10) {
        parts.push(` ... and ${convIds.length - 10} more`)
      }
      parts.push('\n')
    }

    const personas = insight.evidence.affected_personas || []
    if (personas.length > 0) {
      parts.push(`**Affected Personas:** ${personas.join(', ')}\n`)
    }
  }

  // Code recommendation section
  if (insight.code_recommendation) {
    parts.push('\n### Proposed Code Changes\n')
    parts.push(`${insight.code_recommendation.description || ''}\n`)

    const fileChanges = insight.code_recommendation.file_changes || []
    if (fileChanges.length > 0) {
      parts.push('\n#### File Changes\n')
      fileChanges.forEach((change: any, i: number) => {
        parts.push(`\n**${i + 1}. ${change.file || 'unknown'}**\n`)
        parts.push('```diff')
        parts.push(change.diff || 'No diff available')
        parts.push('```\n')
      })
    }
  }

  // Implementation checklist
  parts.push('\n### Implementation Checklist\n')
  const fileChanges = insight.code_recommendation?.file_changes
  if (fileChanges && fileChanges.length > 0) {
    fileChanges.forEach((change: any) => {
      parts.push(`- [ ] Update \`${change.file || 'unknown'}\``)
    })
  } else {
    parts.push('- [ ] Investigate the issue')
    parts.push('- [ ] Implement the fix')
  }
  parts.push('- [ ] Add/update tests')
  parts.push('- [ ] Run simulation to verify fix')
  parts.push('- [ ] Update documentation if needed')

  // Footer
  parts.push(`\n---\n*Generated by AgentSim from [simulation ${simulationId}]()*`)

  return parts.join('\n')
}

export default function CodeRecommendationModal({
  insight,
  simulationId,
  isOpen,
  onClose,
  onIssueCreated,
}: CodeRecommendationModalProps) {
  const [isCreatingIssue, setIsCreatingIssue] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showIssuePreview, setShowIssuePreview] = useState(false)
  const [issueTitle, setIssueTitle] = useState('')
  const [issueBody, setIssueBody] = useState('')

  if (!isOpen || !insight.code_recommendation) return null

  const codeRec = insight.code_recommendation

  const handleOpenPreview = () => {
    // Build default title and body
    const defaultTitle = `[AgentSim] ${insight.title}`
    const defaultBody = buildGithubIssueBody(insight, simulationId)

    setIssueTitle(defaultTitle)
    setIssueBody(defaultBody)
    setShowIssuePreview(true)
  }

  const handleCreateIssue = async () => {
    setIsCreatingIssue(true)
    setError(null)

    try {
      const response = await simulationsApi.createGithubIssue(
        simulationId,
        insight.id,
        { title: issueTitle, body: issueBody }
      )
      onIssueCreated(response.data.issue_url)
      setShowIssuePreview(false)
      // Close modal after success
      setTimeout(() => onClose(), 1500)
    } catch (err: any) {
      console.error('Failed to create GitHub issue:', err)
      setError(err.response?.data?.detail || 'Failed to create GitHub issue')
    } finally {
      setIsCreatingIssue(false)
    }
  }

  return (
    <div
      className="fixed inset-0 bg-navy-900/80 backdrop-blur-sm overflow-y-auto z-50 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <div
        className="relative mx-auto border-2 border-navy-800 w-full max-w-4xl shadow-2xl rounded-lg bg-navy-950 max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="sticky top-0 bg-navy-950 border-b border-navy-800 px-6 py-4 flex justify-between items-start z-10">
          <div>
            <h3 className="text-lg font-semibold text-text-primary">
              Code Recommendation
            </h3>
            <p className="text-sm text-text-tertiary mt-1">{codeRec.title}</p>
          </div>
          <button
            onClick={onClose}
            className="text-text-tertiary hover:text-text-primary text-2xl"
          >
            ×
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-4 space-y-6">
          {/* Description */}
          <div>
            <h4 className="text-sm font-semibold text-text-secondary mb-2">Description</h4>
            <p className="text-sm text-text-tertiary">{codeRec.description}</p>
          </div>

          {/* Priority & Status */}
          <div className="flex gap-4">
            <div>
              <span className="text-xs text-text-muted">Priority:</span>
              <span
                className={`ml-2 px-2 py-1 text-xs rounded ${
                  codeRec.priority === 'high'
                    ? 'bg-red-900/50 text-red-300 border border-red-700'
                    : codeRec.priority === 'medium'
                    ? 'bg-amber-900/50 text-amber-300 border border-amber-700'
                    : 'bg-blue-900/50 text-blue-300 border border-blue-700'
                }`}
              >
                {codeRec.priority}
              </span>
            </div>
            {codeRec.status && (
              <div>
                <span className="text-xs text-text-muted">Status:</span>
                <span className="ml-2 px-2 py-1 text-xs rounded bg-navy-900 text-text-tertiary border border-navy-700">
                  {codeRec.status}
                </span>
              </div>
            )}
          </div>

          {/* File Changes */}
          {codeRec.file_changes && codeRec.file_changes.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold text-text-secondary mb-3">
                Proposed Changes ({codeRec.file_changes.length} file{codeRec.file_changes.length !== 1 ? 's' : ''})
              </h4>
              <div className="space-y-4">
                {codeRec.file_changes.map((change, index) => (
                  <div key={index} className="border border-navy-800 rounded-lg overflow-hidden">
                    {/* File path header */}
                    <div className="bg-navy-900/50 px-4 py-2 border-b border-navy-800">
                      <div className="text-sm font-mono text-strategic-400">{change.file}</div>
                    </div>

                    {/* Diff */}
                    <div className="bg-navy-900">
                      <pre className="text-xs font-mono p-4 overflow-x-auto">
                        <code className="text-text-tertiary">{change.diff}</code>
                      </pre>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* GitHub Issue Link (if already created) */}
          {codeRec.github_issue_url && (
            <div className="bg-green-900/20 border border-green-700 rounded-lg p-4">
              <div className="flex items-center gap-2">
                <span className="text-green-300 font-medium">✓ GitHub Issue Created</span>
              </div>
              <a
                href={codeRec.github_issue_url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-strategic-400 hover:text-strategic-300 underline mt-2 block"
              >
                {codeRec.github_issue_url}
              </a>
            </div>
          )}

          {/* Error Display */}
          {error && (
            <div className="bg-red-900/30 border border-red-700 rounded-lg p-4">
              <div className="text-red-300 font-medium">Error</div>
              <div className="text-sm text-red-200 mt-1">{error}</div>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="sticky bottom-0 bg-navy-950 border-t border-navy-800 px-6 py-4 flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm border border-navy-700 text-text-tertiary rounded hover:bg-navy-900 transition-colors"
          >
            Close
          </button>

          {!codeRec.github_issue_url && (
            <button
              onClick={handleOpenPreview}
              disabled={isCreatingIssue}
              className="px-4 py-2 text-sm bg-cyan-500 text-white rounded hover:bg-cyan-400 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              Create GitHub Issue
            </button>
          )}

          {codeRec.github_issue_url && (
            <a
              href={codeRec.github_issue_url}
              target="_blank"
              rel="noopener noreferrer"
              className="px-4 py-2 text-sm bg-cyan-500 text-white rounded hover:bg-cyan-400 transition-colors"
            >
              View GitHub Issue
            </a>
          )}
        </div>
      </div>

      {/* Issue Preview Dialog */}
      {showIssuePreview && (
        <div
          className="fixed inset-0 bg-navy-900/90 backdrop-blur-sm z-[60] flex items-center justify-center p-4"
          onClick={() => setShowIssuePreview(false)}
        >
          <div
            className="relative mx-auto border-2 border-navy-800 w-full max-w-4xl shadow-2xl rounded-lg bg-navy-950 max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="sticky top-0 bg-navy-950 border-b border-navy-800 px-6 py-4 flex justify-between items-start z-10">
              <div>
                <h3 className="text-lg font-semibold text-text-primary">
                  Preview GitHub Issue
                </h3>
                <p className="text-sm text-text-tertiary mt-1">Edit the title and body before creating</p>
              </div>
              <button
                onClick={() => setShowIssuePreview(false)}
                className="text-text-tertiary hover:text-text-primary text-2xl"
              >
                ×
              </button>
            </div>

            {/* Content */}
            <div className="px-6 py-4 space-y-4">
              {/* Title Input */}
              <div>
                <label className="block text-sm font-semibold text-text-secondary mb-2">
                  Issue Title
                </label>
                <input
                  type="text"
                  value={issueTitle}
                  onChange={(e) => setIssueTitle(e.target.value)}
                  className="w-full px-3 py-2 bg-navy-900 border border-navy-700 rounded text-text-primary focus:outline-none focus:border-strategic-500"
                  placeholder="Enter issue title..."
                />
              </div>

              {/* Body Textarea */}
              <div>
                <label className="block text-sm font-semibold text-text-secondary mb-2">
                  Issue Body (Markdown)
                </label>
                <textarea
                  value={issueBody}
                  onChange={(e) => setIssueBody(e.target.value)}
                  rows={20}
                  className="w-full px-3 py-2 bg-navy-900 border border-navy-700 rounded text-text-primary font-mono text-sm focus:outline-none focus:border-strategic-500 resize-y"
                  placeholder="Enter issue body in markdown format..."
                />
                <p className="text-xs text-text-muted mt-1">
                  Supports markdown formatting (headers, lists, code blocks, etc.)
                </p>
              </div>

              {/* Error Display */}
              {error && (
                <div className="bg-red-900/30 border border-red-700 rounded-lg p-4">
                  <div className="text-red-300 font-medium">Error</div>
                  <div className="text-sm text-red-200 mt-1">{error}</div>
                </div>
              )}
            </div>

            {/* Footer Actions */}
            <div className="sticky bottom-0 bg-navy-950 border-t border-navy-800 px-6 py-4 flex justify-end gap-3">
              <button
                onClick={() => setShowIssuePreview(false)}
                disabled={isCreatingIssue}
                className="px-4 py-2 text-sm border border-navy-700 text-text-tertiary rounded hover:bg-navy-900 transition-colors disabled:opacity-50"
              >
                Cancel
              </button>

              <button
                onClick={handleCreateIssue}
                disabled={isCreatingIssue || !issueTitle.trim() || !issueBody.trim()}
                className="px-4 py-2 text-sm bg-cyan-500 text-white rounded hover:bg-cyan-400 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {isCreatingIssue ? (
                  <>
                    <span className="animate-spin">⟳</span>
                    Creating Issue...
                  </>
                ) : (
                  'Create Issue'
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
