"""
Comprehensive keyword lists for line item classification.

Keeps language-specific terms for both Goods and Services.
"""

from typing import FrozenSet

# Goods indicators (physical products, materials, inventory)
GOODS_INDICATORS: FrozenSet[str] = frozenset(
    {
        # English
        "unit",
        "units",
        "piece",
        "pieces",
        "pcs",
        "each",
        "ea",
        "box",
        "boxes",
        "case",
        "cases",
        "pallet",
        "kg",
        "kilogram",
        "kilograms",
        "lb",
        "lbs",
        "lb.",
        "meter",
        "meters",
        "yard",
        "yardage",
        "pound",
        "pounds",
        "bottle",
        "bottles",
        "can",
        "cans",
        "computer",
        "laptop",
        "phone",
        "equipment",
        "material",
        "materials",
        "supply",
        "supplies",
        "food",
        "beverage",
        "drink",
        "snack",
        "printer",
        "monitor",
        "server",
        "router",
        "furniture",
        "desk",
        "chair",
        "cabinet",
        "inventory",
        "product",
        "products",
        "hardware",
        "peripherals",
        "part",
        "parts",
        "component",
        "components",
        "kit",
        "kits",
        "tool",
        "tools",
        "device",
        "devices",
        "accessory",
        "accessories",
        "appliance",
        "appliances",
        "motor",
        "motors",
        "fabric",
        "fabrics",
        "packing",
        "packaging",
        "tire",
        "tires",
        # Spanish
        "unidad",
        "unidades",
        "pieza",
        "piezas",
        "caja",
        "cajas",
        "botella",
        "botellas",
        "equipo",
        "equipos",
        "material",
        "materiales",
        "suministro",
        "suministros",
        "producto",
        "productos",
        "mueble",
        "muebles",
        "computadora",
        "computadoras",
        "impresora",
        "impresoras",
        "monitor",
        "monitores",
        "pieza",
        "partes",
        "equipo",
        # Portuguese
        "unidade",
        "unidades",
        "peça",
        "peças",
        "caixa",
        "caixas",
        "garrafa",
        "garrafas",
        "equipamento",
        "equipamentos",
        "material",
        "materiais",
        "suprimento",
        "suprimentos",
        "produto",
        "produtos",
        "móvel",
        "móveis",
        "computador",
        "computadores",
        "impresora",
        "papel",
        "caixote",
        # French
        "unité",
        "unités",
        "pièce",
        "pièces",
        "boîte",
        "boîtes",
        "bouteille",
        "bouteilles",
        "équipement",
        "équipements",
        "matériel",
        "composant",
        "composants",
        "meuble",
        "meubles",
        "produit",
        "produits",
        "kit",
        "kits",
        "article",
        "articles",
        # German
        "einheit",
        "einheiten",
        "stück",
        "stücke",
        "kiste",
        "kästen",
        "flasche",
        "flaschen",
        "ausrüstung",
        "material",
        "materialien",
        "produkt",
        "produkte",
        "möbel",
        "computer",
        "gerät",
        "geräte",
        "werkzeug",
        "werkzeuge",
        # Italian
        "unità",
        "pezzo",
        "pezzi",
        "scatola",
        "scatole",
        "bottiglia",
        "bottiglie",
        "attrezzatura",
        "attrezzature",
        "materiale",
        "prodotti",
        "mobile",
        "strumento",
        "strumenti",
        "accessorio",
        "accessori",
        # Dutch
        "eenheid",
        "eenheden",
        "stuk",
        "stuks",
        "doos",
        "dozen",
        "fles",
        "flessen",
        "uitrusting",
        "materiaal",
        "materialen",
        "product",
        "producten",
        "gereedschap",
        # Swedish
        "enhet",
        "enheter",
        "styck",
        "stycken",
        "låda",
        "lådor",
        "flaska",
        "flaskor",
        "utrustning",
        "material",
        "pryl",
        "prylar",
        "verktyg",
        "verktygen",
        # Russian transliteration
        "edinitsa",
        "edinitsy",
        "korobka",
        "butylka",
        "oborudovanie",
        "material",
        "produkt",
        "produkty",
        "detal",
        "detali",
        "instrument",
        # Arabic transliteration
        "wihda",
        "wihdat",
        "qism",
        "kutub",
        "tajhiz",
        "muntaj",
        "mawad",
    }
)

SERVICE_INDICATORS: FrozenSet[str] = frozenset(
    {
        # English
        "consulting",
        "consultation",
        "maintenance",
        "support",
        "subscription",
        "license",
        "licence",
        "professional services",
        "training",
        "service",
        "hourly",
        "monthly",
        "annual",
        "yearly",
        "per month",
        "per year",
        "campaign",
        "campaigns",
        "advertising",
        "ad",
        "ads",
        "media",
        "managed",
        "management",
        "hosting",
        "storage",
        "backup",
        "monitoring",
        "implementation",
        "development",
        "integration",
        "setup",
        "config",
        "billing",
        "retainer",
        "retainers",
        "provisioning",
        "arrangement",
        "sourcing",
        "design",
        "creative",
        "strategy",
        "analysis",
        "coaching",
        # Spanish
        "consultoría",
        "consultor",
        "asesoría",
        "asesoría técnica",
        "soporte",
        "mantenimiento",
        "servicio",
        "servicios",
        "suscripción",
        "licencia",
        "mensual",
        "anual",
        "por hora",
        "por mes",
        "por año",
        "campaña",
        "cobertura",
        "implementación",
        "asesoramiento",
        "capacitación",
        "formación",
        # Portuguese
        "consultoria",
        "consultor",
        "assistência",
        "suporte",
        "manutenção",
        "serviço",
        "serviços",
        "assinatura",
        "licença",
        "mensal",
        "anual",
        "por hora",
        "campanha",
        "implantação",
        "treinamento",
        "consultoria técnica",
        # French
        "consultation",
        "conseil",
        "service",
        "services",
        "maintenance",
        "support",
        "abonnement",
        "licence",
        "annuel",
        "mensuel",
        "par heure",
        "campagne",
        "mise en œuvre",
        "déploiement",
        "formation",
        # German
        "beratung",
        "dienstleistung",
        "dienstleistungen",
        "support",
        "wartung",
        "pflege",
        "abonnement",
        "lizenz",
        "monatlich",
        "jährlich",
        "pro stunde",
        "bereitstellung",
        "installation",
        "schulung",
        "projektmanagement",
        # Italian
        "consulenza",
        "servizio",
        "servizi",
        "manutenzione",
        "supporto",
        "abbonamento",
        "licenza",
        "annuale",
        "mensile",
        "implementazione",
        "formazione",
        "supporto tecnico",
        "gestione",
        "progettazione",
        # Dutch
        "consultancy",
        "dienstverlening",
        "onderhoud",
        "ondersteuning",
        "abonnement",
        "licentie",
        "maandelijks",
        "jaarlijks",
        "per uur",
        "campagne",
        "implementatie",
        "training",
        # Swedish
        "konsult",
        "konsultation",
        "tjänst",
        "tjänster",
        "support",
        "underhåll",
        "abonnemang",
        "licens",
        "per månad",
        "per år",
        "implementering",
        # Russian transliteration
        "konsultatsiya",
        "podderzhka",
        "obsluzhivanie",
        "abonement",
        "litsenziya",
        "servis",
        "podpiska",
        "chasov",
        "v mesyats",
        "v god",
        "obucheniye",
        # Arabic transliteration
        "istishara",
        "khidma",
        "daam",
        "iyadat",
        "iijara",
        "shurta",
        "taklif",
    }
)

# Header patterns for column detection in table-based extraction
# Maps field names to keyword patterns for matching table headers
HEADER_PATTERNS = {
    "description": [
        "description",
        "item",
        "product",
        "service",
        "detail",
        "name",
        "descripción",
        "concepto",
        "detalle",
        "articulo",
        "producto",
        "bezeichnung",
        "beschreibung",
        "article",
        "produit",
    ],
    "quantity": [
        "quantity",
        "qty",
        "qté",
        "cantidad",
        "quantité",
        "menge",
        "qtd",
        "cant",
        "units",
        "unidades",
        "stück",
        "pcs",
        "pieces",
    ],
    "unit_price": [
        "unit price",
        "price",
        "unit",
        "precio",
        "rate",
        "prix unitaire",
        "precio unitario",
        "unit cost",
        "cost",
        "stückpreis",
        "tarifa",
        "vlr unitario",
        "valor unitario",
        "vlr unit",
    ],
    "amount": [
        "amount",
        "total",
        "subtotal",
        "importe",
        "montant",
        "valor",
        "betrag",
        "sum",
        "line total",
        "ext price",
        "extended",
        "monto",
        "vlr total",
        "valor total",
        "valor",
        "vlr",
    ],
    "unit_of_measure": [
        "uom",
        "unit",
        "measure",
        "unidad",
        "medida",
        "um",
        "u/m",
        "unit of measure",
        "unité",
        "einheit",
    ],
    "service_start_date": [
        "from",
        "start",
        "inicio",
        "begin",
        "start date",
        "desde",
        "service from",
        "period start",
        "fecha inicio",
    ],
    "service_end_date": [
        "to",
        "end",
        "fin",
        "through",
        "end date",
        "hasta",
        "thru",
        "service to",
        "period end",
        "fecha fin",
    ],
}

