-- AgentOS Demo Backend Service
DROP SERVICE IF EXISTS AI_FDE.SALES_AI_PLATFORM.AGENTIC_OS_BACKEND;

CREATE SERVICE AI_FDE.SALES_AI_PLATFORM.AGENTIC_OS_BACKEND
IN COMPUTE POOL ${COMPUTE_POOL}
FROM SPECIFICATION $$
spec:
  containers:
  - name: sownvation-htian-backend  
    image: ${REPO_URL}/${IMAGE_NAME}:${IMAGE_TAG}
    env:
      DATABASE: ${DATABASE}
      SCHEMA: ${SCHEMA}
  endpoints:
  - name: api
    port: 8000
    public: true
$$
AUTO_RESUME = TRUE
MIN_INSTANCES = 1
MAX_INSTANCES = 1
QUERY_WAREHOUSE = ${SNOWFLAKE_WAREHOUSE}
EXTERNAL_ACCESS_INTEGRATIONS = (${EXTERNAL_ACCESS_INTEGRATION});
