PRODUCT_MAPPINGS = {
    "AI": {
        "description": "AI and Machine Learning platform including agents, LLM inference, ML operations, search capabilities, and AI-powered analytics functions",
        "subcategories": {
            "AI - Models": {
                "description": "Pre-trained AI models including Arctic family of open-source models",
                "products": [
                    "Yak (Arctic Models)",
                ],
            },
            "AI - Apps, Agents, Search": {
                "description": "AI-powered applications including Cortex Analyst,Cortex Search, MCP (Model Context Protocol), Copilot, Snowflake Intelligence, and Agent APIs",
                "products": ["Agents API", "Cortex Analyst", "Cortex Search", "Inline Copilot", "Snowflake Copilot Chat", "Snowflake Intelligence", "Text2Answers, Text2Chart, Text2Insight", "MCP Server & Client"],
            },
            "AI - Batch & Analytics": {
                "description": "Batch AI processing including ML Functions (Cortex ML), Document AI, and AI-powered SQL functions",
                "products": [
                    "AI Functions",
                    "AI Functions - Multimodal",
                    "AISQL",
                    "Cortex Apps",
                    "Document AI",
                    "ML Functions (Cortex ML)",
                ],
            },
            "AI - Platform": {
                "description": "AI infrastructure including LLM platform, model registry, feature store, ML observability, and fine-tuning capabilities",
                "products": [
                    "AI Gateway",
                    "AI Observability - ML, Agents, LLMs",
                    "Cortex Fine Tuning",
                    "Feature Store (ML Platform)",
                    "LLM Ops (AI Observability)",
                    "LLM Platform (Corvo, Provisioned Throughput)",
                    "ML Lineage (ML Platform)",
                    "Model Registry (ML Platform)",
                    "Notebooks Runtime (ML Platform)",
                    "Online Inference",
                    "REST API - LLM Inference",
                ],
            },
        },
    },
    "Application Platform": {
        "description": "Application development and collaboration platform including Native Apps, Marketplace, Data Sharing, and Data Clean Rooms for secure multi-party collaboration",
        "subcategories": {
            "Apps & Collaboration": {
                "description": "Native Apps framework, Snowflake Marketplace, Data Sharing, and collaboration features",
                "products": [
                    "AI Products",
                    "App Platform",
                    "Data Sharing",
                    "Discovery (Marketplace)",
                    "Internal Collaboration/Internal Marketplace",
                    "Marketplace Trust & Quality",
                    "Native Apps",
                    "Native Apps - Provider",
                    "Snowflake Marketplace",
                ],
            },
            "Data Clean Rooms": {
                "description": "Secure multi-party data collaboration without exposing underlying data",
                "products": [
                    "Data Clean Rooms",
                ],
            },
            "Data Pipelines & Ingestion": {
                "description": "Streaming data ingestion and real-time analytics pipelines",
                "products": [
                    "Streaming Analytics",
                ],
            },
        },
    },
    "Data Analytics": {
        "description": "Core database engine and analytics capabilities including SQL execution, query optimization, OLTP (Unistore), and the foundational database (FDB) infrastructure",
        "subcategories": {
            "APG": {
                "description": "Autonomous Performance Guidance for query optimization recommendations",
                "products": [
                    "APG",
                ],
            },
            "Analytics": {
                "description": "SQL query execution, optimization, workload management, data types, and advanced analytics functions",
                "products": [
                    "DML (Insert, Update, Merge, Delete)",
                    "Large Warehouses (5XL/6XL)",
                    "Migrations",
                    "SQL Advanced Analytics (incl. time series)",
                    "SQL Compiler",
                    "SQL Data Types (Geospatial, Numbers, Variants, Structured Types, Timestamps)",
                    "SQL Execution",
                    "SQL Frameworks",
                    "SQL Optimizer",
                    "SQL Search (pruning, search optimization, full text search)",
                    "SQL Workload Optimization (QAS, Clustering, MVs, Workload Insights)",
                    "SQL-Query-Language",
                    "Semantic Views",
                ],
            },
            "FDB": {
                "description": "FoundationDB - distributed database infrastructure powering Snowflake's metadata and transaction layers",
                "products": [
                    "FDB",
                    "FDB Access (FKA Persistence Services)",
                    "FDB Core",
                    "FDB DevProd",
                    "FDB Foundation",
                    "FDB Metacluster",
                    "FDB Performance",
                    "FDB Platform",
                    "FDB Security",
                    "FDB Storage",
                ],
            },
            "Unistore": {
                "description": "Hybrid tables and OLTP (Online Transaction Processing) capabilities for transactional workloads",
                "products": [
                    "HTAP Observability",
                    "Plan Cache",
                    "Unistore",
                    "Unistore - Query Processing",
                    "Unistore - Services",
                    "Unistore - Storage",
                    "Unistore - Workloads",
                    "Unistore Performance",
                ],
            },
        },
    },
    "Data Engineering": {
        "description": "Data integration and transformation platform including connectors, Snowpark compute, data pipelines, developer tools (drivers, APIs), and storage management",
        "subcategories": {
            "Connectivity": {
                "description": "Data connectors for SaaS applications, databases, streaming sources, and unstructured data",
                "products": [
                    "Apache Nifi & SDK",
                    "Database Connectors",
                    "Openflow Connectors",
                    "SaaS Connectors",
                    "Snowflake Openflow",
                    "Streaming Connectors",
                    "Unstructured Connectors",
                ],
            },
            "Data Pipelines": {
                "description": "Streams, Tasks, Dynamic Tables, and pipeline orchestration",
                "products": [
                    "Dynamic Tables",
                    "Schema Detection & Inference",
                    "Streams",
                    "Tasks",
                ],
            },
            "Data Pipelines & Ingestion": {
                "description": "Streaming data ingestion and real-time analytics pipelines",
                "products": [
                    "COPY",
                    "Data Platform: Data Pipelines",
                    "Snowpipe",
                    "Snowpipe Streaming",
                ],
            },
            "Developer Platform": {
                "description": "Drivers (Python, Java, Node.js, JDBC, ODBC), REST APIs, Terraform, SnowCLI, and developer tools",
                "products": [
                    ".Net Driver",
                    "DCM (Database Change Management)",
                    "Drivers (general)",
                    "Drivers - Client Backend",
                    "Go Driver",
                    "JDBC Driver",
                    "Libsfclient Driver",
                    "NodeJS Driver",
                    "ODBC Driver",
                    "PHP Driver",
                    "Python Driver",
                    "SnowAPIs: Python API",
                    "SnowAPIs: REST API",
                    "SnowAPIs: SQL REST API",
                    "SnowCLI",
                    "SnowGit",
                    "SnowSQL",
                    "Terraform Provider",
                    "Universal Driver",
                ],
            },
            "Snowpark": {
                "description": "Serverless compute for Python, Java, Scala, and JavaScript with UDFs, stored procedures, and external access",
                "products": [
                    "Snowpark: Aggregate Functions",
                    "Snowpark: Application Development Ecosystem",
                    "Snowpark: Compute Infrastructure",
                    "Snowpark: External Access",
                    "Snowpark: External Functions",
                    "Snowpark: Java/Scala UDFs & Stored Procs",
                    "Snowpark: JavaScript UDFs & Stored Procs",
                    "Snowpark: Python Snowpark Client",
                    "Snowpark: SCLS Control Plane",
                    "Snowpark: SCLS Data Plane",
                    "Snowpark: SCOS",
                    "Snowpark: Secure Sandbox",
                    "Snowpark: Translators",
                    "Snowpark: User Code & Language Environments - Core",
                ],
            },
            "Storage": {
                "description": "Object storage management, archival storage, and stage replication",
                "products": [
                    "Archival Storage",
                    "Stage Replication",
                    "Storage",
                    "Unstructured Data Management",
                ],
            },
        },
    },
    "Metadata": {
        "description": "Metadata management framework including entity management, cloning, replication, time travel, and the metadata catalog infrastructure",
        "subcategories": {
            "Metadata": {
                "description": "Metadata dictionary framework, entity management, cloning, replication, time travel, and catalog services",
                "products": [
                    "Bundles",
                    "Cloning",
                    "EP",
                    "Entity / Dictionary Framework",
                    "Entity / TableColumnTemplate",
                    "EntityDPO Caching",
                    "Metadata Consistency Checker MDCC",
                    "Replication (account | client failover, business continuity...)",
                    "SHOW / Fetch / Infoschema Catalog",
                    "Time Travel",
                    "Transactions",
                ],
            },
        },
    },
    "Open Lakehouse": {
        "description": "Open data lakehouse capabilities including Iceberg tables, external tables, and connectors for Delta Lake and Apache Hive formats",
        "subcategories": {
            "Data Lake & Storage": {
                "description": "Iceberg tables, external tables, Delta Lake and Hive connectors, and data lake export",
                "products": [
                    "Data Lake Connectors (Delta, Hive)",
                    "Data Lake Export",
                    "External Tables",
                    "Iceberg projects",
                    "Storage COGS",
                ],
            },
        },
    },
    "Billing & Monetization Platform": {
        "description": "Billing, metering, rating, invoicing, and contract management platform for Snowflake's monetization infrastructure",
        "subcategories": {
            "Billing and Monetization Platform": {
                "description": "End-to-end billing system including contracting, metering, rating, invoicing, and integrations",
                "products": [
                    "BP Platform - Contracting",
                    "BP Platform - Customer Experience",
                    "BP Platform - Integrations",
                    "BP Platform - Invoicing",
                    "BP Platform - Metering",
                    "BP Platform - Rating",
                ],
            },
        },
    },
    "Governance | Manageability | Privacy | Security": {
        "description": "Security, governance, and compliance infrastructure including authentication, encryption, RBAC, data privacy, access policies, data lineage, and regulatory compliance (RSC)",
        "subcategories": {
            "DB Security": {
                "description": "Database security including authentication, encryption, RBAC, secrets management, and network security",
                "products": [
                    "Auditing",
                    "Authentication, Single sign-on (SSO), Identity management",
                    "Encryption, HSM, Tri-secret secure (TSS)",
                    "Network security & private connectivity",
                    "RBAC",
                    "Secrets, External API Authentication",
                    "Trust Center",
                ],
            },
            "Data Governance": {
                "description": "Data classification, access policies, data lineage, data quality, privacy, and object tagging",
                "products": [
                    "Access History / Audit",
                    "Auto Description",
                    "Classification",
                    "Data Access Policies",
                    "Data Lineage / Object Dependencies",
                    "Data Privacy (contains differential privacy)",
                    "Data Quality",
                    "Object Tagging",
                    "Synthetic Data",
                ],
            },
            "Global Platform": {
                "description": "SnowCommand platform, Organizations, Snowflake DB, and global management services",
                "products": [
                    "Organizations / Global Platform",
                    "SnowCommand Billing Tooling",
                    "SnowCommand Engineering Tooling",
                    "SnowCommand Parameters",
                    "SnowCommand Platform",
                    "SnowCommand Sales Tooling",
                    "SnowCommand Support Tooling",
                    "Snowflake DB",
                    "Snowhouse Data Ingestion",
                    "Snowlink",
                ],
            },
            "Product Security": {
                "description": "Product security engineering, employee production access (EPA), cloud security, and anti-abuse",
                "products": [
                    "AGM",
                    "Anti Abuse",
                    "Assurance",
                    "Cloud Security",
                    "Employee Production Access",
                    "Employee Production Access - IdP Proxy",
                    "FUSE Secrets - Secret Management",
                    "FUSE Snowidentity - workload identity",
                    "Hashicorp Vault",
                ],
            },
            "Regulatory & Sovereign Cloud (RSC)": {
                "description": "Compliance and sovereign cloud infrastructure for regulated industries",
                "products": [
                    "RSC - Cloud Platform",
                    "RSC - Compliance",
                ],
            },
        },
    },
    "Platform & Infrastructure Engineering": {
        "description": "Cloud infrastructure and platform services including compute provisioning (SPCS), networking, observability, capacity management, release engineering, and production control plane",
        "subcategories": {
            "Engineering Systems": {
                "description": "CI/CD, build systems (Bazel, Buildbarn), testing infrastructure, performance tooling, and development environments",
                "products": [
                    "Java and GS dependency clean up",
                    "ArtifactInfra",
                    "Bazel",
                    "Buildbarn",
                    "Cloud Workspace",
                    "Continuous Integration (CI), Precommit & PR Health & Code Coverage",
                    "Crashmanager on Zonal/Galactic Snowhouse",
                    "Hermetic Test Infrastructure",
                    "JenkinsInfra",
                    "Perf Tooling",
                    "QE Stability",
                    "Regression Tests on AWS GovCloud",
                    "Releng to QA Transition",
                    "SUT (System Under Test)",
                    "Shift Left",
                    "Snowfort",
                    "Snowtrail",
                    "Thermoscope",
                    "Type Faster",
                ],
            },
            "PIE: Capacity, Performance & Efficiency (CPE)": {
                "description": "Capacity planning, performance optimization, efficiency/COGS management, and CSP relationships",
                "products": [
                    "CSP Relationship",
                    "Capacity",
                    "Cloud Catalog",
                    "Efficiency/COGS/Tinyhouse",
                    "Performance",
                    "Supercluster",
                ],
            },
            "PIE: Cost Governance & Optimization": {
                "description": "Cost optimization services and governance for cloud resources",
                "products": [
                    "Optimization Services",
                ],
            },
            "PIE: External Compute": {
                "description": "Snowpark Container Services (SPCS) for running containerized workloads and custom applications",
                "products": [
                    "Async Task Queue",
                    "SPCS Core",
                    "SPCS Ecosystem - ML",
                    "SPCS Ecosystem - Native Apps",
                    "SPCS Ecosystem - Observability",
                    "SPCS Ecosystem - User Model",
                    "Secure Code Execution",
                    "Snowservices - Billing",
                    "Snowservices - Compute Provisioning",
                    "Snowservices - Container Orchestrator",
                    "Snowservices - Image Registry",
                    "Snowservices - Network Egress",
                    "Snowservices - Network Ingress",
                ],
            },
            "PIE: Internal Compute": {
                "description": "Internal compute infrastructure including Java platform, EGS (Elastic Global Services), and container platform",
                "products": [
                    "Background Services",
                    "Container Platform",
                    "Dedicated Services",
                    "EGS (Elastic Global Services)",
                    "GS XP Communication",
                    "Java Platform",
                    "Job",
                ],
            },
            "PIE: Managed Services": {
                "description": "Managed databases (Postgres, Redis) for internal platform services",
                "products": [
                    "Managed databased: Postgres/Redis",
                ],
            },
            "PIE: Operating Systems": {
                "description": "OS engineering, machine images, and operating system management",
                "products": [
                    "OS Engineering",
                ],
            },
            "PIE: Production Control Plane": {
                "description": "Deployment lifecycle, control plane (Avalanche), and production infrastructure management",
                "products": [
                    "CPS",
                    "Control Plane / Avalanche",
                    "Deployment Lifecycle Management",
                    "Temptest",
                ],
            },
            "PIE: Reliability, Release & Observability": {
                "description": "Observability stack, release engineering, experiments, parameters, and production engineering",
                "products": [
                    "Cloud Health",
                    "Experiments",
                    "Observability - Collection & Consumption",
                    "Observability - Ingestion & Storage",
                    "Parameters",
                    "Production Engineering",
                    "Release Engineering - Health Checker",
                    "Release Engineering - Parameter Automation",
                    "Release Engineering - Release Orchestrator",
                    "Release Engineering - Release Pipeline",
                ],
            },
            "PIE: Traffic": {
                "description": "DNS, ingress, egress, service discovery, networking, and certificate management",
                "products": [
                    "Certificate Management",
                    "Core networking & platform",
                    "DNS",
                    "Discovery (Service Discovery)",
                    "Egress",
                    "Ingress",
                ],
            },
            "Service Stability Review": {
                "description": "Production engineering and service stability practices",
                "products": [
                    "Cloud Engineering - Production Engineering",
                ],
            },
        },
    },
    "Product Experiences": {
        "description": "User interfaces and experiences including Snowsight, Worksheets, Notebooks, Dashboards, Streamlit, and workload-specific experiences",
        "subcategories": {
            "Developer Platform": {
                "description": "Drivers (Python, Java, Node.js, JDBC, ODBC), REST APIs, Terraform, SnowCLI, and developer tools",
                "products": [
                    "VS Code Extension",
                ],
            },
            "Product Experiences": {
                "description": "User interfaces including Snowsight, Worksheets, Notebooks, Dashboards, Streamlit, and workload-specific experiences",
                "products": [
                    "APEX Foundations",
                    "Analytics",
                    "App Foundation",
                    "Apps Stability & Infra",
                    "Compute Experience",
                    "Core UI",
                    "Dashboards (APEX)",
                    "Data Engineering Experience",
                    "Data Observability",
                    "Documentation Platform",
                    "Growth Platform",
                    "Notebooks",
                    "On-Demand Growth",
                    "PE Platform Backend",
                    "PE Platform Core Objects",
                    "PE Platform UI",
                    "PSG Experience",
                    "PSGEX",
                    "Snowsight App",
                    "Streamlit",
                    "Streamlit Hub / Community Cloud",
                    "Streamlit Open Source Library",
                    "Streamlit-in-Snowflake (APEX)",
                    "Support within Snowflake (SwS)",
                    "UI Platform",
                    "UI Upgrade (Classic > Snowsight)",
                    "Worksheets",
                    "Workspaces",
                ],
            },
        },
    },
}
