CREATE COMPUTE POOL IF NOT EXISTS <% SPCS_COMPUTE_POOL_NAME %>
    MIN_NODES = 1
    MAX_NODES = 1
    INSTANCE_FAMILY = CPU_X64_XS
    AUTO_SUSPEND_SECS = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE IMAGE REPOSITORY IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.<% SPCS_IMAGE_REPO_NAME %>;

CREATE STAGE IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.<% SPCS_STAGE_NAME %>
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
