CREATE TABLE IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.KB_KNOWLEDGE (
    SYS_ID STRING PRIMARY KEY,
    KB_NUMBER STRING,
    SHORT_DESCRIPTION STRING,
    TEXT STRING,
    KNOWLEDGE_BASE STRING,
    CATEGORY STRING,
    ACTIVE BOOLEAN DEFAULT TRUE,
    LATEST BOOLEAN DEFAULT TRUE,
    CAN_READ_USER_CRITERIA STRING,
    CANNOT_READ_USER_CRITERIA STRING,
    SYS_CREATED_ON TIMESTAMP_NTZ,
    SYS_UPDATED_ON TIMESTAMP_NTZ,
    PROCESSING_VERSION STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.KB_CHUNKS (
    KB_SYS_ID STRING NOT NULL,
    KB_NUMBER STRING,
    CHUNK_INDEX NUMBER,
    CHUNK_TEXT STRING,
    SHORT_DESCRIPTION STRING,
    KNOWLEDGE_BASE STRING,
    CAN_READ_USER_CRITERIA STRING,
    CANNOT_READ_USER_CRITERIA STRING,
    PROCESSING_VERSION STRING,
    SOURCE_UPDATED_ON TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (KB_SYS_ID, CHUNK_INDEX)
);

CREATE TABLE IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.SEARCH_QUERIES (
    QUERY_ID STRING PRIMARY KEY DEFAULT UUID_STRING(),
    QUERY_TEXT STRING,
    RESPONSE_TEXT STRING,
    CONTEXT VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.SEARCH_FEEDBACK (
    FEEDBACK_ID STRING PRIMARY KEY DEFAULT UUID_STRING(),
    QUERY_ID STRING REFERENCES <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.SEARCH_QUERIES(QUERY_ID),
    RATING NUMBER,
    COMMENTS STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.GOLDEN_PAIRS (
    PAIR_ID STRING PRIMARY KEY DEFAULT UUID_STRING(),
    QUESTION STRING,
    EXPECTED_ANSWER STRING,
    KB_SYS_ID STRING,
    KB_NUMBER STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.EVALUATION_RESULTS (
    EVAL_ID STRING PRIMARY KEY DEFAULT UUID_STRING(),
    PAIR_ID STRING REFERENCES <% KB_DATABASE_NAME %>.<% KB_SCHEMA_NAME %>.GOLDEN_PAIRS(PAIR_ID),
    GENERATED_ANSWER STRING,
    SIMILARITY_SCORE FLOAT,
    METRICS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
