CREATE OR REPLACE CORTEX SEARCH SERVICE {{ KB_DATABASE_NAME }}.{{ KB_SCHEMA_NAME }}.KB_SEARCH
    ON CHUNK_TEXT
    ATTRIBUTES KB_SYS_ID, KB_NUMBER, CHUNK_INDEX, KNOWLEDGE_BASE, CAN_READ_USER_CRITERIA, CANNOT_READ_USER_CRITERIA, PROCESSING_VERSION
    WAREHOUSE = {{ KB_WAREHOUSE_NAME }}
    TARGET_LAG = '1 hour'
AS (
    SELECT
        KB_SYS_ID,
        KB_NUMBER,
        CHUNK_INDEX,
        CHUNK_TEXT,
        SHORT_DESCRIPTION,
        KNOWLEDGE_BASE,
        CAN_READ_USER_CRITERIA,
        CANNOT_READ_USER_CRITERIA,
        PROCESSING_VERSION,
        SOURCE_UPDATED_ON
    FROM {{ KB_DATABASE_NAME }}.{{ KB_SCHEMA_NAME }}.KB_CHUNKS
);
