CREATE NETWORK RULE IF NOT EXISTS {{ KB_DATABASE_NAME }}.{{ KB_SCHEMA_NAME }}.CDN_JSDELIVR_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('cdn.jsdelivr.net:443');

CREATE NETWORK RULE IF NOT EXISTS {{ KB_DATABASE_NAME }}.{{ KB_SCHEMA_NAME }}.SERVICENOW_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('{{ SERVICENOW_INSTANCE_HOST }}:443');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION {{ SPCS_EAI_NAME }}
    ALLOWED_NETWORK_RULES = (
        {{ KB_DATABASE_NAME }}.{{ KB_SCHEMA_NAME }}.CDN_JSDELIVR_RULE,
        {{ KB_DATABASE_NAME }}.{{ KB_SCHEMA_NAME }}.SERVICENOW_RULE
    )
    ENABLED = true;
