#!/bin/bash

# Get the current git commit hash
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Generate version.go with the commit hash
cat > cmd/p67/version_gen.go << EOF
// Code generated by build.sh. DO NOT EDIT.
package main

func init() {
	commit = "${COMMIT}"
}
EOF

echo "Generated version_gen.go with commit: ${COMMIT}"

# Build the binary
mkdir -p bin
go build -o bin/p67 ./cmd/p67

echo "Build complete: bin/p67"
