services:
  # The n8n service for running your workflow
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=http://localhost:5678/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_SECURE_COOKIE=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=true
    volumes:
      - ./n8n/workflows:/home/node/.n8n/workflows
      - n8n_data:/home/node/.n8n

  # The REST-to-gRPC Gateway service
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8080:80"
    environment:
      - FILESTORE_GRPC_URL=filestore:50051
      - INVOICESTORE_GRPC_URL=invoicestore:50051
    depends_on:
      - filestore
      - invoicestore
    develop:
      watch:
        - action: sync
          path: ./gateway/app
          target: /inviq/gateway/app
        - action: sync
          path: ./py-protos/src
          target: /inviq/py-protos/src

  # The Collector service
  collector:
    build:
      context: .
      dockerfile: ./collector/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FILESTORE_GRPC_URL=filestore:50051
      - INVOICESTORE_GRPC_URL=invoicestore:50051
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/default
    depends_on:
      - filestore
      - invoicestore
      - n8n
      - gateway
    develop:
      watch:
        - action: sync
          path: ./collector/app
          target: /inviq/collector/app
        - action: sync
          path: ./py-protos/src
          target: /inviq/py-protos/src

  # The gRPC FileStore service
  filestore:
    build:
      context: .
      dockerfile: ./filestore/Dockerfile
    develop:
      watch:
        - action: sync
          path: ./filestore/app
          target: /inviq/filestore/app
        - action: sync
          path: ./py-protos/src
          target: /inviq/py-protos/src
        - action: sync
          path: ./py-util/src
          target: /inviq/py-util/src

  # The gRPC InvoiceStore service
  invoicestore:
    build:
      context: .
      dockerfile: ./invoicestore/Dockerfile
    develop:
      watch:
        - action: sync
          path: ./invoicestore/app
          target: /inviq/invoicestore/app
        - action: sync
          path: ./py-protos/src
          target: /inviq/py-protos/src
        - action: sync
          path: ./py-util/src
          target: /inviq/py-util/src

volumes:
  n8n_data:
