.phony: fix check

check:
	make check -C ./py-util
	make check -C ./invoicestore
	make check -C ./filestore
	make check -C ./collector
	make check -C ./extractor
	make check -C ./larry

fix:
	make fix -C ./py-util
	make fix -C ./invoicestore
	make fix -C ./filestore
	make fix -C ./collector
	make fix -C ./extractor
	make fix -C ./larry
