# API ports
DEFAULT_API_PORT = 8000
DEFAULT_FRONTEND_PORT = 3000

# CORS origins for development
ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Database defaults
DEFAULT_TABLE_PREVIEW_LIMIT = 10
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 1000

# Snowflake defaults
DEFAULT_WAREHOUSE = "COMPUTE_WH"
DEFAULT_SCHEMA = "PUBLIC"
DEFAULT_ROLE = "SYSADMIN"

# Analytics
DEFAULT_PERIOD_DAYS = 30
MAX_ANALYTICS_ROWS = 10000
