-- Network rule for Python service (CDN access)
CREATE NETWORK RULE IF NOT EXISTS <% SPCS_DATABASE_NAME %>.<% SPCS_SCHEMA_NAME %>.CDN_JSDELIVR_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('cdn.jsdelivr.net:443');

-- Network rule for example job (public APIs)
CREATE NETWORK RULE IF NOT EXISTS <% SPCS_DATABASE_NAME %>.<% SPCS_SCHEMA_NAME %>.PUBLIC_API_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('api.publicapis.org:443', 'httpbin.org:443');

-- External access integration for both services
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION <% SPCS_EAI_NAME %>
  ALLOWED_NETWORK_RULES = (
    <% SPCS_DATABASE_NAME %>.<% SPCS_SCHEMA_NAME %>.CDN_JSDELIVR_RULE,
    <% SPCS_DATABASE_NAME %>.<% SPCS_SCHEMA_NAME %>.PUBLIC_API_RULE
  )
  ENABLED = true;
