-- Create compute pool and image repository
CREATE COMPUTE POOL IF NOT EXISTS ${COMPUTE_POOL}
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_SUSPEND_SECS = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE IMAGE REPOSITORY IF NOT EXISTS ${DATABASE}.${SCHEMA}.${IMAGE_REPOSITORY};

-- Create stage for service specs if needed
CREATE STAGE IF NOT EXISTS ${DATABASE}.${SCHEMA}.${STAGE}
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
