-- Dashboard service
DROP SERVICE IF EXISTS ${DATABASE}.${SCHEMA}.${DASHBOARD_SERVICE_NAME};

CREATE SERVICE ${DATABASE}.${SCHEMA}.${DASHBOARD_SERVICE_NAME}
IN COMPUTE POOL ${COMPUTE_POOL}
FROM SPECIFICATION $$
spec:
  containers:
    - name: dashboard
      image: ${REPO_URL}/${DASHBOARD_IMAGE_NAME}:${IMAGE_TAG}
      env:
        ENV: "PROD"
        SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
        AUTHENTICATION_METHOD: "SNOWFLAKE_TOKEN"
        SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
        SNOWFLAKE_DATABASE: ${DATABASE}
        SNOWFLAKE_SCHEMA: ${SCHEMA}
        SNOWFLAKE_ROLE: ${ROLE}
        
  endpoints:
    - name: ui
      port: 8501
      public: true
$$
MIN_INSTANCES = 1
MAX_INSTANCES = 1
AUTO_RESUME = TRUE
EXTERNAL_ACCESS_INTEGRATIONS = ();
