USE ROLE invoiceiq_admin;
USE DATABASE invoiceiq;
USE SCHEMA service;

CREATE OR REPLACE TABLE INVOICEIQ.SERVICE.INVOICES (
	INVOICE_ID VARCHAR(16777216) DEFAULT UUID_STRING() PRIMARY KEY,
	RELATIVE_PATH VARCHAR(16777216) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(16777216) DEFAULT 'PENDING',
	SUBMISSION_ID VARCHAR(16777216),
	TICKET_NUMBER VARCHAR(16777216),
	BANKING_DETAILS VARCHAR(16777216),
	DUE_DATE DATE,
	FILE_URL VARCHAR(16777216),
	FREIGHT_SHIPPING_AMOUNT NUMBER(38,2),
	INVOICE_CURRENCY VARCHAR(16777216),
	INVOICE_DATE DATE,
	INVOICE_NUMBER VARCHAR(16777216),
	MEMO_DESCRIPTION VARCHAR(16777216),
	PAYMENT_TERMS VARCHAR(16777216),
	PAYMENT_TYPE VARCHAR(16777216),
	PREPAID_FLAG BOOLEAN,
	PURCHASE_ORDER_NUMBER VARCHAR(16777216),
	QUANTITY NUMBER(38,4),
	SERVICE_END_DATE DATE,
	SERVICE_START_DATE DATE,
	SHIPPED_TO_ADDRESS VARCHAR(16777216),
	SNOWFLAKE_ENTITY VARCHAR(16777216),
	SNOWFLAKE_TAX_ID VARCHAR(16777216),
	TAX_AMOUNT NUMBER(38,2),
	TOTAL_AMOUNT NUMBER(38,2),
	UNIT_PRICE NUMBER(38,4),
	VENDOR_ADDRESS VARCHAR(16777216),
	VENDOR_NAME VARCHAR(16777216),
	VENDOR_TAX_ID VARCHAR(16777216),
	LAST_EDITED_BY VARCHAR(16777216),
	LAST_EDITED_AT TIMESTAMP_NTZ(9),
	AI_DECISION VARCHAR(16777216),
	AI_REASONING VARCHAR(16777216),
	AI_PROCESSED_AT TIMESTAMP_NTZ(9),
	CONSTRAINT FK_INVOICE_FILE_METADATA FOREIGN KEY (RELATIVE_PATH) REFERENCES INVOICEIQ.SERVICE.FILE_METADATA(RELATIVE_PATH)
);

-- Create a queue table for invoice processing
-- Results from the STREAM will be put here for processing
CREATE OR REPLACE TABLE INVOICEIQ.SERVICE.INVOICE_PROCESSING_QUEUE (
	INVOICE_ID VARCHAR(16777216),
	AI_PROCESSED_AT TIMESTAMP_NTZ(9),
	METADATA$ACTION VARCHAR(16777216),
	METADATA$ISUPDATE VARCHAR(16777216),
	INSERTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE INDEX IF NOT EXISTS IDX_INVOICES_RELATIVE_PATH ON INVOICEIQ.SERVICE.INVOICES(RELATIVE_PATH);
CREATE INDEX IF NOT EXISTS IDX_INVOICES_STATUS ON INVOICEIQ.SERVICE.INVOICES(STATUS);
CREATE INDEX IF NOT EXISTS IDX_INVOICES_SUBMISSION_ID ON INVOICEIQ.SERVICE.INVOICES(SUBMISSION_ID);
CREATE INDEX IF NOT EXISTS IDX_INVOICES_TICKET_NUMBER ON INVOICEIQ.SERVICE.INVOICES(TICKET_NUMBER);

CREATE STREAM IF NOT EXISTS INVOICEIQ.SERVICE.INVOICES_STREAM ON TABLE INVOICEIQ.SERVICE.INVOICES;

GRANT SELECT, INSERT, UPDATE, DELETE ON INVOICEIQ.SERVICE.INVOICES TO ROLE INVOICEIQ_ADMIN;
GRANT SELECT ON INVOICEIQ.SERVICE.INVOICE_WITH_EXTRACTION TO ROLE INVOICEIQ_ADMIN;