name: collector-ci

on:
  pull_request:
    branches: [main]
    paths:
      - "inviq/collector/**/*"
  push:
    branches:
      - "**"
    paths:
      - "inviq/collector/**/*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Run checks
        working-directory: inviq/collector
        run: make check
