name: knowledge-builder-ci

on:
  push:
    branches:
      - "**"
    paths:
      - "knowledge-builder/**/*"
      - ".github/workflows/knowledge-builder-ci.yml"
      - ".github/actions/setup-rust/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./knowledge-builder

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          rust-version: stable

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --verbose
